services:
# Share unix sockets
  tmp:
   image: busybox
   command: chmod -R 777 /tmp/docker
   volumes:
     - /tmp/docker/

  mysql:
    image: mysql:8.3
    restart: always
    container_name: mysql
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysql:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
    volumes_from:
      - tmp
    networks:
      - laravel-development

  phpmyadmin:
   image: phpmyadmin/phpmyadmin:latest
       container_name: phpMyAdmin
       restart: always
   depends_on:
     - mysql
   environment:
     PMA_HOST: mysql
     MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
   volumes_from:
      - tmp
   ports:
      - "81:80"
  networks:
   - laravel-development

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbit-broker
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: kalo
      RABBITMQ_DEFAULT_PASS: kalo
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - laravel-development

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - laravel-development

  web:
    privileged: true
    image: macbre/nginx-http3:latest
    restart: always
    volumes_from:
      - tmp
    volumes:
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www
    ports:
      - "80:80"
      - "443:443/udp"
      - "443:443/tcp"
    environment:
      - NGINX_HOST=codeanalyzer.bronk-ict.nl
    networks:
      - laravel-development
    depends_on:
      php-fpm:
        condition: service_started # Wait for php-fpm to start

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      # Mount the application code for live updates
      - ./:/var/www
    volumes_from:
      - tmp
    networks:
      - laravel-development
    restart: always
    depends_on:
      mysql:
        condition: service_started # Wait for MYSQL postgres to start
      redis:
        condition: service_started

  workspace:
    privileged: true
    build:
      context: .
      dockerfile: ./docker/development/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    restart: always
    tty: true # Enables an interactive terminal
    stdin_open: true # Keeps standard input open for 'docker exec'
    volumes_from:
      - tmp
    volumes:
      - ./:/var/www
    networks:
      - laravel-development

  ollama:
    container_name: ollama
    image: ollama/ollama # Replace with specific Ollama version if needed
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always
    networks:
      - laravel-development

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server /var/redis/redis.conf #--save 20 1 --loglevel warning --requirepass password
    volumes:
      - cache:/data
      - ./redis.conf:/var/redis/redis.conf
    volumes_from:
      - tmp
    networks:
      - laravel-development

networks:
  laravel-development:
    enable_ipv6: true

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  mysql:
    driver: local
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
  ollama:
    driver: local
  cache:
    driver: local
